targets:
    $default:
        builders:
            json_serializable:
                generate_for:
                    - lib/**.dart
                options:
                    generic_argument_factories: true
                    explicit_to_json: true
            source_gen:combining_builder:
                options:
                    build_extensions:
                        '^lib/data/models/{{file}}.dart': 'lib/data/models/generated/{{file}}.g.dart'
