targets:
    $default:
        builders:
            json_serializable:
                generate_for:
                    - lib/**.dart
                options:
                    generic_argument_factories: true
                    explicit_to_json: true
            source_gen:combining_builder:
                options:
                    build_extensions:
                        '^lib/data/models/{{dir}}/{{file}}.dart': 'lib/data/models/{{dir}}/generated/{{file}}.g.dart'
                        '^lib/data/data_sources/local/db/adapters/{{file}}.dart': 'lib/data/data_sources/local/db/adapters/generated/{{file}}.g.dart'
                        '^lib/data/remote/services/responses/{{file}}.dart': 'lib/data/remote/services/responses/generated/{{file}}.g.dart'
