name: flutter_boilerplate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get: 4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^2.0.0
  json_serializable: ^6.8.0
  keyboard_dismisser: ^3.0.0
  pretty_dio_logger: ^1.4.0
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
